# -*- mode: ruby -*-
# vi: set ft=ruby :
#

#  Clinica General  Infraestructura completa
#  Alumno: Alejandro Sanchez Araujo  2 ASIR
#
#  Maquinas
#    - SGBD        10.0.20.10  
#    - NFS         10.0.30.40  
#    - Backend 1   10.0.30.10  
#    - Backend 2   10.0.30.20  
#    - Balanceador 10.0.50.10  
#    - Router      10.0.50.40  
#                  10.0.60.40
#    - FTP         10.0.60.20  


Vagrant.configure("2") do |config|


  config.vm.define "sgbd" do |sgbd|
    sgbd.vm.box      = "ubuntu/jammy64"
    sgbd.vm.hostname = "sgbd-clinica"
    sgbd.vm.network "private_network",
      ip:      "10.0.20.10",
      netmask: "255.255.254.0"
    sgbd.vm.provider "virtualbox" do |vb|
      vb.name   = "SGBD-Clinica"
      vb.memory = 1024
      vb.cpus   = 2
    end
    sgbd.vm.provision "shell", path: "provision/sgbd.sh"
  end

  # NFS 
  config.vm.define "nfs" do |nfs|
    nfs.vm.box      = "ubuntu/jammy64"
    nfs.vm.hostname = "nfs-clinica"
    nfs.vm.network "private_network",
      ip:      "10.0.30.40",
      netmask: "255.255.254.0"
    nfs.vm.provider "virtualbox" do |vb|
      vb.name   = "NFS-Clinica"
      vb.memory = 512
      vb.cpus   = 1
    end
    nfs.vm.provision "shell", path: "provision/nfs.sh"
  end

  # BACKEND 1 
  config.vm.define "backend1" do |b1|
    b1.vm.box      = "ubuntu/jammy64"
    b1.vm.hostname = "backend1-clinica"
    b1.vm.network "private_network",
      ip:      "10.0.30.10",
      netmask: "255.255.254.0"
    b1.vm.network "private_network",
      ip:      "10.0.20.20",
      netmask: "255.255.254.0"
    b1.vm.provider "virtualbox" do |vb|
      vb.name   = "Backend1-Clinica"
      vb.memory = 1024
      vb.cpus   = 2
    end
    b1.vm.provision "shell", path: "provision/backend.sh",
      env: { "HOSTNAME_VM" => "backend1-clinica" }
  end

  # BACKEND 2 
  config.vm.define "backend2" do |b2|
    b2.vm.box      = "ubuntu/jammy64"
    b2.vm.hostname = "backend2-clinica"
    b2.vm.network "private_network",
      ip:      "10.0.30.20",
      netmask: "255.255.254.0"
    b2.vm.network "private_network",
      ip:      "10.0.20.30",
      netmask: "255.255.254.0"
    b2.vm.provider "virtualbox" do |vb|
      vb.name   = "Backend2-Clinica"
      vb.memory = 1024
      vb.cpus   = 2
    end
    b2.vm.provision "shell", path: "provision/backend.sh",
      env: { "HOSTNAME_VM" => "backend2-clinica" }
  end

  #  BALANCEADOR 
  config.vm.define "balanceador" do |bal|
    bal.vm.box      = "ubuntu/jammy64"
    bal.vm.hostname = "balanceador-clinica"
    bal.vm.network "private_network",
      ip:      "10.0.50.10",
      netmask: "255.255.254.0"
    bal.vm.network "private_network",
      ip:      "10.0.30.30",
      netmask: "255.255.254.0"
    bal.vm.provider "virtualbox" do |vb|
      vb.name   = "Balanceador-Clinica"
      vb.memory = 512
      vb.cpus   = 2
    end
    bal.vm.provision "shell", path: "provision/balanceador.sh"
  end

  #  ROUTER 
  config.vm.define "router" do |router|
    router.vm.box      = "ubuntu/jammy64"
    router.vm.hostname = "router-clinica"
    router.vm.network "private_network",
      ip:      "10.0.50.40",
      netmask: "255.255.254.0"
    router.vm.network "private_network",
      ip:      "10.0.60.40",
      netmask: "255.255.254.0"
    router.vm.provider "virtualbox" do |vb|
      vb.name   = "Router-Clinica"
      vb.memory = 256
      vb.cpus   = 1
    end
    router.vm.provision "shell", path: "provision/router.sh"
  end

  #  FTP 
  config.vm.define "ftp" do |ftp|
    ftp.vm.box      = "ubuntu/jammy64"
    ftp.vm.hostname = "ftp-clinica"
    ftp.vm.network "private_network",
      ip:      "10.0.60.20",
      netmask: "255.255.254.0"
    ftp.vm.provider "virtualbox" do |vb|
      vb.name   = "FTP-Clinica"
      vb.memory = 512
      vb.cpus   = 1
    end
    ftp.vm.provision "shell", path: "provision/ftp.sh"
  end

end